config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'api/api'

Rails.application.routes.draw do
  if Gitlab::Sherlock.enabled?
    namespace :sherlock do
      resources :transactions, only: [:index, :show] do
        resources :queries, only: [:show]
        resources :file_samples, only: [:show]

        collection do
          delete :destroy_all
        end
      end
    end
  end

  if Rails.env.development?
    # Make the built-in Rails routes available in development, otherwise they'd
    # get swallowed by the `namespace/project` route matcher below.
    #
    # See https://git.io/va79N
    get '/rails/mailers'         => 'rails/mailers#index'
    get '/rails/mailers/:path'   => 'rails/mailers#preview'
    get '/rails/info/properties' => 'rails/info#properties'
    get '/rails/info/routes'     => 'rails/info#routes'
    get '/rails/info'            => 'rails/info#index'

    mount LetterOpenerWeb::Engine, at: '/rails/letter_opener'
  end

  namespace :ci do
    # CI API
    Ci::API::API.logger Rails.logger
    mount Ci::API::API => '/api'

    resource :lint, only: [:show, :create]

    resources :projects do
      member do
        get :status, to: 'projects#badge'
        get :integration
      end
    end

    root to: 'projects#index'
  end

  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications',
                authorizations: 'oauth/authorizations'
  end

  # Autocomplete
  get '/autocomplete/users' => 'autocomplete#users'
  get '/autocomplete/users/:id' => 'autocomplete#user'

  # Emojis
  resources :emojis, only: :index

  # Search
  get 'search' => 'search#show'
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete

  # JSON Web Token
  get 'jwt/auth' => 'jwt#auth'

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
  end

  # Health check
  get 'health_check(/:checks)' => 'health_check#index', as: :health_check

  # Enable Grack support
  mount Grack::AuthSpawner, at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post, :put]

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }
  get 'help/shortcuts'
  get 'help/ui' => 'help#ui'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get 'raw'
    end
  end

  get '/s/:username', to: redirect('/u/%{username}/snippets'),
                      constraints: { username: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }

  #
  # Invites
  #

  resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
    member do
      post :accept
      match :decline, via: [:get, :post]
    end
  end

  resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
    member do
      get :unsubscribe
    end
  end

  # Spam reports
  resources :abuse_reports, only: [:new, :create]

  #
  # Import
  #
  namespace :import do
    resource :github, only: [:create, :new], controller: :github do
      get :status
      get :callback
      get :jobs
    end

    resource :gitlab, only: [:create, :new], controller: :gitlab do
      get :status
      get :callback
      get :jobs
    end

    resource :bitbucket, only: [:create, :new], controller: :bitbucket do
      get :status
      get :callback
      get :jobs
    end

    resource :gitorious, only: [:create, :new], controller: :gitorious do
      get :status
      get :callback
      get :jobs
    end

    resource :google_code, only: [:create, :new], controller: :google_code do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end

    resource :fogbugz, only: [:create, :new], controller: :fogbugz do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end
  end

  #
  # Uploads
  #

  scope path: :uploads do
    # Note attachments and User/Group/Project avatars
    get ":model/:mounted_as/:id/:filename",
        to:           "uploads#show",
        constraints:  { model: /note|user|group|project/, mounted_as: /avatar|attachment/, filename: /[^\/]+/ }

    # Appearance
    get ":model/:mounted_as/:id/:filename",
        to:           "uploads#show",
        constraints:  { model: /appearance/, mounted_as: /logo|header_logo/, filename: /.+/ }

    # Project markdown uploads
    get ":namespace_id/:project_id/:secret/:filename",
      to:           "projects/uploads#show",
      constraints:  { namespace_id: /[a-zA-Z.0-9_\-]+/, project_id: /[a-zA-Z.0-9_\-]+/, filename: /[^\/]+/ }
  end

  # Redirect old note attachments path to new uploads path.
  get "files/note/:id/:filename",
    to:           redirect("uploads/note/attachment/%{id}/%{filename}"),
    constraints:  { filename: /[^\/]+/ }

  #
  # Explore area
  #
  namespace :explore do
    resources :projects, only: [:index] do
      collection do
        get :trending
        get :starred
      end
    end

    resources :groups, only: [:index]
    resources :snippets, only: [:index]
    root to: 'projects#trending'
  end

  # Compatibility with old routing
  get 'public' => 'explore/projects#index'
  get 'public/projects' => 'explore/projects#index'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      resources :keys, only: [:show, :destroy]
      resources :identities, except: [:show]

      member do
        get :projects
        get :keys
        get :groups
        put :team_update
        put :block
        put :unblock
        put :unlock
        put :confirm
        post :impersonate
        patch :disable_two_factor
        delete 'remove/:email_id', action: 'remove_email', as: 'remove_email'
      end
    end

    resource :impersonation, only: :destroy

    resources :abuse_reports, only: [:index, :destroy]
    resources :spam_logs, only: [:index, :destroy]

    resources :applications

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :members_update
      end
    end

    resources :deploy_keys, only: [:index, :new, :create, :destroy]

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :edit, :create, :update, :destroy] do
      post :preview, on: :collection
    end

    resource :logs, only: [:show]
    resource :health_check, controller: 'health_check', only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :namespaces, path: '/projects', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
      root to: 'projects#index', as: :projects

      resources(:projects,
                path: '/',
                constraints: { id: /[a-zA-Z.0-9_\-]+/ },
                only: [:index, :show]) do
        root to: 'projects#show'

        member do
          put :transfer
          post :repository_check
        end

        resources :runner_projects
      end
    end

    resource :appearances, path: 'appearance' do
      member do
        get :preview
        delete :logo
        delete :header_logos
      end
    end

    resource :application_settings, only: [:show, :update] do
      resources :services
      put :reset_runners_token
      put :reset_health_check_token
      put :clear_repository_check_states
    end

    resources :labels

    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        get :resume
        get :pause
      end
    end

    resources :builds, only: :index do
      collection do
        post :cancel_all
      end
    end

    root to: 'dashboard#index'
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :audit_log
      get :applications, to: 'oauth/applications#index'

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update] do
        member do
          delete :unlink
        end
      end
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resource :preferences, only: [:show, :update]
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
      resource :two_factor_auth, only: [:new, :create, :destroy] do
        member do
          post :codes
          patch :skip
        end
      end
    end
  end

  scope(path: 'u/:username',
        as: :user,
        constraints: { username: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ },
        controller: :users) do
    get :calendar
    get :calendar_activities
    get :groups
    get :projects
    get :contributed, as: :contributed_projects
    get :snippets
    get '/', action: :show
  end

  #
  # Dashboard Area
  #
  resource :dashboard, controller: 'dashboard', only: [] do
    get :issues
    get :merge_requests
    get :activity

    scope module: :dashboard do
      resources :milestones, only: [:index, :show]
      resources :labels, only: [:index]

      resources :groups, only: [:index]
      resources :snippets, only: [:index]

      resources :todos, only: [:index, :destroy] do
        collection do
          delete :destroy_all
        end
      end

      resources :projects, only: [:index] do
        collection do
          get :starred
        end
      end
    end

    root to: "dashboard/projects#index"
  end

  #
  # Groups Area
  #

app/controllers/import/base_controller.rb
class Import::BaseController < ApplicationController

  private

  def get_or_create_namespace
    begin
      namespace = Group.create!(name: @target_namespace, path: @target_namespace, owner: current_user)
      namespace.add_owner(current_user)
    rescue ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvalid
      namespace = Namespace.find_by_path_or_name(@target_namespace)
      unless current_user.can?(:create_projects, namespace)
        @already_been_taken = true
        return false
      end
    end

    namespace
  end
end

app/controllers/import/bitbucket_controller.rb
class Import::BitbucketController < Import::BaseController
  before_action :verify_bitbucket_import_enabled
  before_action :bitbucket_auth, except: :callback

  rescue_from OAuth::Error, with: :bitbucket_unauthorized
  rescue_from Gitlab::BitbucketImport::Client::Unauthorized, with: :bitbucket_unauthorized

  def callback
    request_token = session.delete(:oauth_request_token)
    raise "Session expired!" if request_token.nil?

    request_token.symbolize_keys!

    access_token = client.get_token(request_token, params[:oauth_verifier], callback_import_bitbucket_url)

    session[:bitbucket_access_token] = access_token.token
    session[:bitbucket_access_token_secret] = access_token.secret

    redirect_to status_import_bitbucket_url
  end

  def status
    @repos = client.projects
    @incompatible_repos = client.incompatible_projects

    @already_added_projects = current_user.created_projects.where(import_type: "bitbucket")
    already_added_projects_names = @already_added_projects.pluck(:import_source)

    @repos.to_a.reject!{ |repo| already_added_projects_names.include? "#{repo["owner"]}/#{repo["slug"]}" }
  end

  def jobs
    jobs = current_user.created_projects.where(import_type: "bitbucket").to_json(only: [:id, :import_status])
    render json: jobs
  end

  def create
    @repo_id = params[:repo_id] || ""
    repo = client.project(@repo_id.gsub("___", "/"))
    @project_name = repo["slug"]

    repo_owner = repo["owner"]
    repo_owner = current_user.username if repo_owner == client.user["user"]["username"]
    @target_namespace = params[:new_namespace].presence || repo_owner

    namespace = get_or_create_namespace || (render and return)

    unless Gitlab::BitbucketImport::KeyAdder.new(repo, current_user, access_params).execute
      @access_denied = true
      render
      return
    end

    @project = Gitlab::BitbucketImport::ProjectCreator.new(repo, namespace, current_user, access_params).execute
  end

  private

  def client
    @client ||= Gitlab::BitbucketImport::Client.new(session[:bitbucket_access_token],
                                                    session[:bitbucket_access_token_secret])
  end

  def verify_bitbucket_import_enabled
    render_404 unless bitbucket_import_enabled?
  end

  def bitbucket_auth
    if session[:bitbucket_access_token].blank?
      go_to_bitbucket_for_permissions
    end
  end

  def go_to_bitbucket_for_permissions
    request_token = client.request_token(callback_import_bitbucket_url)
    session[:oauth_request_token] = request_token

    redirect_to client.authorize_url(request_token, callback_import_bitbucket_url)
  end

  def bitbucket_unauthorized
    go_to_bitbucket_for_permissions
  end

  private

  def access_params
    {
      bitbucket_access_token: session[:bitbucket_access_token],
      bitbucket_access_token_secret: session[:bitbucket_access_token_secret]
    }
  end
end

app/controllers/import/fogbugz_controller.rb
class Import::FogbugzController < Import::BaseController
  before_action :verify_fogbugz_import_enabled
  before_action :user_map, only: [:new_user_map, :create_user_map]

  rescue_from Fogbugz::AuthenticationException, with: :fogbugz_unauthorized

  def new

  end

  def callback
    begin
      res = Gitlab::FogbugzImport::Client.new(import_params.symbolize_keys)
    rescue
      # If the URI is invalid various errors can occur
      return redirect_to new_import_fogbugz_path, alert: '无法连接 FogBugz，请检查你的链接'
    end
    session[:fogbugz_token] = res.get_token
    session[:fogbugz_uri] = params[:uri]

    redirect_to new_user_map_import_fogbugz_path
  end

  def new_user_map

  end

  def create_user_map
    user_map = params[:users]

    unless user_map.is_a?(Hash) && user_map.all? { |k, v| !v[:name].blank? }
      flash.now[:alert] = '所有用户必须有一个名字。'

      render 'new_user_map' and return
    end

    session[:fogbugz_user_map] = user_map

    flash[:notice] = '用户映射已保存。请选择要导入的项目继续。'

    redirect_to status_import_fogbugz_path
  end

  def status
    unless client.valid?
      return redirect_to new_import_fogbugz_path
    end

    @repos = client.repos

    @already_added_projects = current_user.created_projects.where(import_type: 'fogbugz')
    already_added_projects_names = @already_added_projects.pluck(:import_source)

    @repos.reject! { |repo| already_added_projects_names.include? repo.name }
  end

  def jobs
    jobs = current_user.created_projects.where(import_type: 'fogbugz').to_json(only: [:id, :import_status])
    render json: jobs
  end

  def create
    @repo_id = params[:repo_id]
    repo = client.repo(@repo_id)
    fb_session = { uri: session[:fogbugz_uri], token: session[:fogbugz_token] }
    @target_namespace = current_user.namespace
    @project_name = repo.name

    namespace = @target_namespace

    umap = session[:fogbugz_user_map] || client.user_map

    @project = Gitlab::FogbugzImport::ProjectCreator.new(repo, fb_session, namespace, current_user, umap).execute
  end

  private

  def client
    @client ||= Gitlab::FogbugzImport::Client.new(token: session[:fogbugz_token], uri: session[:fogbugz_uri])
  end

  def user_map
    @user_map ||= begin
      user_map = client.user_map

      stored_user_map = session[:fogbugz_user_map]
      user_map.update(stored_user_map) if stored_user_map

      user_map
    end
  end

  def fogbugz_unauthorized(exception)
    redirect_to new_import_fogbugz_path, alert: exception.message
  end

  def import_params
    params.permit(:uri, :email, :password)
  end

  def verify_fogbugz_import_enabled
    render_404 unless fogbugz_import_enabled?
  end
end

app/helpers/import_helper.rb
module ImportHelper
  def github_project_link(path_with_namespace)
    link_to path_with_namespace, github_project_url(path_with_namespace), target: '_blank'
  end

  private

  def github_project_url(path_with_namespace)
    "#{github_root_url}/#{path_with_namespace}"
  end

  def github_root_url
    return @github_url if defined?(@github_url)

    provider = Gitlab.config.omniauth.providers.find { |p| p.name == 'github' }
    @github_url = provider.fetch('url', 'https://github.com') if provider
  end
end

app/views/import/google_code/new.html.haml
- page_title "Google 代码导入"
- header_title "项目", root_path
%h3.page-title
  %i.fa.fa-google
  从 Google 代码导入项目
%hr

= form_tag callback_import_google_code_path, class: 'form-horizontal', multipart: true do
  %p
    按照下面的步骤来导入 Google Code 项目数据。
    在下一步，请先选择要导入的项目。
  %ol
    %li
      %p
        转到
        #{link_to "下载数据 (Google Takeout)", "https://www.google.com/settings/takeout", target: "_blank"}.
    %li
      %p
        请先确保已登录到要导入项目的账号。
    %li
      %p
        先在右侧点击<strong>全部不选</strong>按钮，以保证只选择“Google 代码 Project Hosting”选项.
    %li
      %p
        向下滚动到 <strong>Google 代码 Project Hosting</strong>，在右边开启选择。
    %li
      %p
        在页面底部点击<strong>下一步</strong>。
    %li
      %p
        “文件类型”与“投放方式”选项保持其默认值即可。
    %li
      %p
        点击<strong>创建归档文件</strong>，然后等待归档完成。
    %li
      %p
        点击<strong>下载</strong>按钮，然后等待下载完成。
    %li
      %p
        找到下载的 ZIP 文件再解压。
    %li
      %p
        找到新解压出来的 <code>Takeout/Google代码Project Hosting/Google代码ProjectHosting.json</code> 文件。
    %li
      %p
        上传 <code>Google代码ProjectHosting.json</code> 到这里：
      %p
        %input{type: "file", name: "dump_file", id: "dump_file"}
    %li
      %p
        是否想自定义 Google 代码邮箱地址和用户名导入到 GitLab？
      %p
        = label_tag :create_user_map_0 do
          = radio_button_tag :create_user_map, 0, true
          否，直接导入到已存在的邮箱地址和用户名。
      %p
        = label_tag :create_user_map_1 do
          = radio_button_tag :create_user_map, 1, false
          是，映射 Google 代码用户到完整的姓名或 GitLab 用户。
    %li
      %p
        = submit_tag '继续下一步', class: "btn btn-create"

app/views/import/google_code/new_user_map.html.haml
- page_title "用户映射", "Google 代码导入"
- header_title "项目", root_path
%h3.page-title
  %i.fa.fa-google
  从 Google 代码导入项目
%hr

= form_tag create_user_map_import_google_code_path, class: 'form-horizontal' do
  %p
    自定义 Google 代码邮箱地址和用户名导入到 GitLab。
    下一步，请先选择要导入的项目。
  %p
    The user map is a JSON document mapping the Google Code users that participated on your projects to the way their email addresses and usernames will be imported into GitLab. You can change this by changing the value on the right hand side of <code>:</code>. Be sure to preserve the surrounding double quotes, other punctuation and the email address or username on the left hand side.
  %ul
    %li
      %strong 默认：直接导入 Google 代码邮箱地址或用户名
      %p
        <code>"johnsmith@example.com": "johnsm...@example.com"</code>
        will add "By johnsm...@example.com" to all issues and comments originally created by johnsmith@example.com.
        The email address or username is masked to ensure the user's privacy.
    %li
      %strong 映射 Google 代码用户到 GitLab 用户
      %p
        <code>"johnsmith@example.com": "@johnsmith"</code>
        will add "By <a href="#">@johnsmith</a>" to all issues and comments originally created by johnsmith@example.com,
        and will set <a href="#">@johnsmith</a> as the assignee on all issues originally assigned to johnsmith@example.com.
    %li
      %strong 映射 Google 代码用户到完整姓名
      %p
        <code>"johnsmith@example.com": "John Smith"</code>
        will add "By John Smith" to all issues and comments originally created by johnsmith@example.com.
    %li
      %strong 映射 Google 代码用户到完整邮箱地址
      %p
        <code>"johnsmith@example.com": "johnsmith@example.com"</code>
        will add "By <a href="#">johnsmith@example.com</a>" to all issues and comments originally created by johnsmith@example.com.
        By default, the email address or username is masked to ensure the user's privacy. Use this option if you want to show the full email address.

  .form-group
    .col-sm-12
      = text_area_tag :user_map, JSON.pretty_generate(@user_map), class: 'form-control', rows: 15

  .form-actions
    = submit_tag '继续下一步', class: "btn btn-create"

app/views/import/google_code/status.html.haml
- page_title "Google 代码导入"
- header_title "项目", root_path
%h3.page-title
  %i.fa.fa-google
  从 Google 代码导入项目

- if @repos.any?
  %p.light
    选择要导入的项目。
  %p.light
    可选项，可以
    = link_to "自定义", new_user_map_import_google_code_path
    Google 代码邮箱地址和用户名来导入到 GitLab。
  %hr
  %p
  - if @incompatible_repos.any?
    = button_tag class: "btn btn-import btn-success js-import-all" do
      导入所有兼容项目
      = icon("spinner spin", class: "loading-icon")
  - else
    = button_tag class: "btn btn-import btn-success js-import-all" do
      导入所有项目
      = icon("spinner spin", class: "loading-icon")

.table-responsive
  %table.table.import-jobs
    %colgroup.import-jobs-from-col
    %colgroup.import-jobs-to-col
    %colgroup.import-jobs-status-col
    %thead
      %tr
        %th 从 Google 代码
        %th 到 GitLab
        %th 状态
    %tbody
      - @already_added_projects.each do |project|
        %tr{id: "project_#{project.id}", class: "#{project_status_css_class(project.import_status)}"}
          %td
            = link_to project.import_source, "https://code.google.com/p/#{project.import_source}", target: "_blank"
          %td
            = link_to project.path_with_namespace, [project.namespace.becomes(Namespace), project]
          %td.job-status
            - if project.import_status == 'finished'
              %span
                %i.fa.fa-check
                完成
            - elsif project.import_status == 'started'
              %i.fa.fa-spinner.fa-spin
              已开始
            - else
              = project.human_import_status_name

      - @repos.each do |repo|
        %tr{id: "repo_#{repo.id}"}
          %td
            = link_to repo.name, "https://code.google.com/p/#{repo.name}", target: "_blank"
          %td.import-target
            = "#{current_user.username}/#{repo.name}"
          %td.import-actions.job-status
            = button_tag class: "btn btn-import js-add-to-import" do
              导入
              = icon("spinner spin", class: "loading-icon")
      - @incompatible_repos.each do |repo|
        %tr{id: "repo_#{repo.id}"}
          %td
            = link_to repo.name, "https://code.google.com/p/#{repo.name}", target: "_blank"
          %td.import-target
          %td.import-actions-job-status
            = label_tag "不兼容项目", nil, class: "label label-danger"

- if @incompatible_repos.any?
  %p
    因为有些项目使用 Subversion(svn) 或 Mercurial(hg) 版本控制
    而不是 Git，所以无法导入到 GitLab。
    请在 Google 代码上通过
    = link_to "导入工作流", new_import_google_code_path
    将其转换成 Git 后再试。

:javascript
  new ImporterStatus("#{jobs_import_google_code_path}", "#{import_google_code_path}");